---
- name: Package sources
  synology_dsm_api_request:
    api_name: SYNO.Core.Package.Feed
    api_method: add
    request_method: POST
    api_params:
      # This value is expected to be double JSON encoded
      list: '{{ { "name": item.name, "feed": item.feed } | to_json | to_json }}'
  when: item.name not in (synology_dsm_package_sources_list.json.data['items'] | map(attribute='name'))
  loop: '{{ synology_dsm_package_sources }}'
  loop_control:
    label: '{{ item.name }}'
