---
- name: wrapper block
  module_defaults:
    synology_dsm_api_request:
      base_url: '{{ synology_dsm_base_url }}'
      login_cookie: '{{ synology_dsm_login_cookie | default(omit) }}'
  block:
    - include_tasks: api/auth/login.yml

    # Figure out the API
    # - include_tasks: api/info.yml

    # Get system status info
    - include_tasks: system/status.yml

    # Control the terminal access
    # - include_tasks: terminal.yml

    # List all users
    # - include_tasks: core/user/list.yml

    # Create a user
    # - include_tasks: core/user/create.yml

    # Delete users
    # - include_tasks: core/user/delete.yml

    # Set mail configurations
    # - include_tasks: notif/mail/conf/set.yml

    # Add a package source
    # - include_tasks: core/package/feed/add.yml

    # Set specific file services & protocols
    # - include_tasks: core/fileserv/afp/set.yml
    # - include_tasks: core/fileserv/nfs/set.yml
    # - include_tasks: core/fileserv/smb/set.yml

    - include_tasks: api/auth/logout.yml
