---
- name: Set Password Policy
  synology_dsm_api_request:
    api_name: SYNO.Entry.Request
    api_method: request
    request_method: POST
    api_params:
      stop_on_error: 'false'
      mode: sequential
      compound: >-
        [
          {
            "api": "SYNO.Core.User.PasswordPolicy",
            "method": "set",
            "version": "1",
            "enable_reset_passwd_by_email": false,
            "password_must_change": false,
            "strong_password": {
              "exclude_username": true,
              "included_numeric_char": false,
              "included_special_char": false,
              "min_length_enable": true,
              "min_length": 6,
              "mixed_case": true,
              "exclude_common_password": false,
              "exclude_history": false
            }
          }
        ]

