---
- name: Delete { {{ del_users | expand_users }} }
  synology_dsm_api_request:
    api_name: SYNO.Entry.Request
    api_method: request
    request_method: POST
    api_params:
      stop_on_error: 'false'
      mode: sequential
      compound: >-
        [
          {
            "api": "SYNO.Core.User",
            "method": "delete",
            "version": "1",
            {{ del_users | expand_users }}
          }
        ]

# 3101: means the user may not be locate-able
# returns 3102 if success
