---
- name: Set Password Expiration
  synology_dsm_api_request:
    api_name: SYNO.Entry.Request
    api_method: request
    request_method: POST
    api_params:
      stop_on_error: 'false'
      mode: sequential
      compound: >-
        [
          {
            "api": "SYNO.Core.User.PasswordExpiry",
            "method": "set",
            "version": "1",
            "password_expire_enable": false
          }
        ]
